"""Initial schema

Revision ID: 192f043aefe6
Revises: 
Create Date: 2026-09-30 08:01:09.111115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '192f043aefe6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spells',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('school', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('time', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('range', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('components', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('material', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
    sa.Column('duration', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('concentration', sa.Boolean(), nullable=False),
    sa.Column('ritual', sa.Boolean(), nullable=False),
    sa.Column('hit', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('effect', sqlmodel.sql.sqltypes.AutoString(length=750), nullable=False),
    sa.Column('desc', sqlmodel.sql.sqltypes.AutoString(length=10000), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spells_level'), 'spells', ['level'], unique=False)
    op.create_index(op.f('ix_spells_name'), 'spells', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('player', 'dm', 'admin', name='role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('dm_id', sa.Integer(), nullable=False),
    sa.Column('image_data_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('first_session_date', sa.Date(), nullable=True),
    sa.Column('session_number', sa.Integer(), nullable=False),
    sa.Column('ingame_days', sa.Integer(), nullable=False),
    sa.Column('book_page', sa.Integer(), nullable=True),
    sa.Column('level_min', sa.Integer(), nullable=True),
    sa.Column('level_max', sa.Integer(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dm_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.Enum('pc', 'npc', name='characterkind'), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaign_characters',
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('campaign_id', 'character_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('campaign_characters')
    op.drop_table('characters')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_spells_name'), table_name='spells')
    op.drop_index(op.f('ix_spells_level'), table_name='spells')
    op.drop_table('spells')
    # ### end Alembic commands ###
